### 1. Importar librerías y paquetes

In [1]:
# Importar librerias
import pandas as pd
import unicodedata
import os

### 2. Importar datos de origen

#### 2.1 Importar datos de Instalaciones de Galicia

In [2]:
# Importar datos de instalaciones de Galicia
df_instalaciones_galicia = pd.read_excel("../Data/Raw/Public/MITECO/Galicia_InformeInstalaciones_04092026.xlsx")

# Visualizar los resultados
df_instalaciones_galicia

,Clave Registro,Nombre de Instalación,Municipio de la Instalación,Provincia de la Instalación,Número de fase,Número de Registro Autonómico Definitivo,Potencia Instalada KW,Grupo Normativo,Tipo de Inscripción,Fecha de Inscripción Definitiva
0,RE-000057,FEIXA I,Ponte Caldelas,Pontevedra,1,RE-99-15,1500.0,b.4,DEFINITIVA,1999-04-19 00:00:00
1,RE-000058,FEIXA II,Ponte Caldelas,Pontevedra,2,RE-99-16,4950.0,b.4,DEFINITIVA,2003-05-22 00:00:00
2,RE-000058,FEIXA II,Ponte Caldelas,Pontevedra,1,RE-99-16,5000.0,b.4,DEFINITIVA,1999-04-19 00:00:00
3,RE-000072,ALMOFREI,Cotobade,Pontevedra,1,RE-05-54,1200.0,b.4,DEFINITIVA,1999-04-19 00:00:00
4,RE-000073,PONTE INFERNO,Soutomaior,Pontevedra,1,RE-05-5,4200.0,b.4,DEFINITIVA,1999-04-19 00:00:00
...,...,...,...,...,...,...,...,...,...,...
1147,RE-99D-631,COGENERACION KAUMAN,Ponteareas,Pontevedra,1,RE-99-33,2700.0,a.1.2,DEFINITIVA,1999-09-10 00:00:00
1148,RE-99D-634,MADERAS MENDAÑA,Pontedeume,La Coruña,1,RE-99-34,2384.0,a.1.2,DEFINITIVA,1999-09-22 00:00:00
1149,RE-99D-635,ATRENESTE,Monforte de Lemos,Lugo,1,RE-99-35,1520.0,a.1.2,DEFINITIVA,1999-09-28 00:00:00
1150,RE-99D-647,CAMPO BRICK,Mesía,La Coruña,1,RE-99-55,4095.0,a.1.1,DEFINITIVA,1999-12-15 00:00:00
1151,RE-99D-647,CAMPO BRICK,Mesía,La Coruña,2,RP-26-05,2450.0,b.1.1,DEFINITIVA,2026-03-18 00:00:00

#### 2.2 Importar datos de Provincias

In [3]:
# Importar datos de Provincias (del INE)
df_provincias = pd.read_excel(
    "../Data/Silver/D_provincias_ine.xlsx"
)

df_provincias = df_provincias[['Id_provincia', 'Id_ccaa', 'Cod-prv', 'Nombre_provincia',
       'Nombre_provincia_st', 'Nombre_provincia_completo']]

# Visualizar los resultados
df_provincias

,Id_provincia,Id_ccaa,Cod-prv,Nombre_provincia,Nombre_provincia_st,Nombre_provincia_completo
0,01-04,1,4,Almería,Almeria,01-04 - Almería
1,01-11,1,11,Cádiz,Cadiz,01-11 - Cádiz
2,01-14,1,14,Córdoba,Cordoba,01-14 - Córdoba
3,01-18,1,18,Granada,Granada,01-18 - Granada
4,01-21,1,21,Huelva,Huelva,01-21 - Huelva
5,01-23,1,23,Jaén,Jaen,01-23 - Jaén
6,01-29,1,29,Málaga,Malaga,01-29 - Málaga
7,01-41,1,41,Sevilla,Sevilla,01-41 - Sevilla
8,02-22,2,22,Huesca,Huesca,02-22 - Huesca
9,02-44,2,44,Teruel,Teruel,02-44 - Teruel
10,02-50,2,50,Zaragoza,Zaragoza,02-50 - Zaragoza
11,03-33,3,33,Asturias,Asturias,03-33 - Asturias
12,04-07,4,7,Illes Balears,Illes Balears,04-07 - Illes Balears
13,05-35,5,35,Las Palmas,Las Palmas,05-35 - Las Palmas
14,05-38,5,38,Santa Cruz de Tenerife,Santa Cruz de Tenerife,05-38 - Santa Cruz de Tenerife
15,06-39,6,39,Cantabria,Cantabria,06-39 - Cantabria
16,07-05,7,5,Ávila,Avila,07-05 - Ávila
17,07-09,7,9,Burgos,Burgos,07-09 - Burgos
18,07-24,7,24,León,Leon,07-24 - León
19,07-34,7,34,Palencia,Palencia,07-34 - Palencia
20,07-37,7,37,Salamanca,Salamanca,07-37 - Salamanca
21,07-40,7,40,Segovia,Segovia,07-40 - Segovia
22,07-42,7,42,Soria,Soria,07-42 - Soria
23,07-47,7,47,Valladolid,Valladolid,07-47 - Valladolid
24,07-49,7,49,Zamora,Zamora,07-49 - Zamora
25,08-02,8,2,Albacete,Albacete,08-02 - Albacete
26,08-13,8,13,Ciudad Real,Ciudad Real,08-13 - Ciudad Real
27,08-16,8,16,Cuenca,Cuenca,08-16 - Cuenca
28,08-19,8,19,Guadalajara,Guadalajara,08-19 - Guadalajara
29,08-45,8,45,Toledo,Toledo,08-45 - Toledo
30,09-08,9,8,Barcelona,Barcelona,09-08 - Barcelona
31,09-17,9,17,Girona,Girona,09-17 - Girona
32,09-25,9,25,Lleida,Lleida,09-25 - Lleida
33,09-43,9,43,Tarragona,Tarragona,09-43 - Tarragona
34,10-03,10,3,Alicante / Alacant,Alicante / Alacant,10-03 - Alicante / Alacant
35,10-12,10,12,Castellón / Castelló,Castellon / Castello,10-12 - Castellón / Castelló
36,10-46,10,46,Valencia / València,Valencia / Valencia,10-46 - Valencia / València
37,11-06,11,6,Badajoz,Badajoz,11-06 - Badajoz
38,11-10,11,10,Cáceres,Caceres,11-10 - Cáceres
39,12-15,12,15,A Coruña,A Coruna,12-15 - A Coruña
40,12-27,12,27,Lugo,Lugo,12-27 - Lugo
41,12-32,12,32,Ourense,Ourense,12-32 - Ourense
42,12-36,12,36,Pontevedra,Pontevedra,12-36 - Pontevedra
43,13-28,13,28,Madrid,Madrid,13-28 - Madrid
44,14-30,14,30,Murcia,Murcia,14-30 - Murcia
45,15-31,15,31,Navarra,Navarra,15-31 - Navarra
46,16-01,16,1,Araba / Álava,Araba / Alava,16-01 - Araba / Álava
47,16-20,16,20,Gipuzkoa,Gipuzkoa,16-20 - Gipuzkoa
48,16-48,16,48,Bizkaia,Bizkaia,16-48 - Bizkaia
49,17-26,17,26,La Rioja,La Rioja,17-26 - La Rioja
50,18-51,18,51,Ceuta,Ceuta,18-51 - Ceuta
51,19-52,19,52,Melilla,Melilla,19-52 - Melilla

#### 2.3 Importar datos de Propietarios

In [4]:
# Importar datos de propietarios de instalaciones (del INEGA)
df_propietarios_instalaciones = pd.read_excel(
    "../Data/Raw/Public/INEGA/INEGA_Centrales_Eolicas_Galicia_202606.xlsx"
)

# Visualizar los resultados
df_propietarios_instalaciones.head(5)

,Central_eolica,Potencia_neta_kw,Propietario,Registro_inega,Fecha_puesta_marcha,Ayuntamiento,Ambito_provincial,Tipo_instalacion,Fuente,Fecha_fuente,Id_Propietario
0,P.E. MONTE SOMOZAS,49600,"Energías Ambientales de Somozas, S.A.",RE-05-100,2000,As Somozas,A Coruña,Parque eólico,INEGA - Centrales eólicas operativas en Galicia,2026-06,PROP_008
1,P.E. MONTE REDONDO,49500,"Naturgy Renovables, S.L.U.",RE-05-98,2001,Vimianzo,A Coruña,Parque eólico,INEGA - Centrales eólicas operativas en Galicia,2026-06,PROP_038
2,P.E. MUXÍA I,46000,"EDP Renovables España, S.L.",RP-18-02,2018,Muxía,A Coruña,Parque eólico,INEGA - Centrales eólicas operativas en Galicia,2026-06,PROP_004
3,P.E. PEDREGAL TREMUZO (IF),44600,"Iberdrola Energías Renovables de Galicia, S.A.",RE-04-12,2003,"Mazaricos, Muros, Outes",A Coruña,Parque eólico,INEGA - Centrales eólicas operativas en Galicia,2026-06,PROP_033
4,P.E. CORZÁN,43200,"Enel Green Power España, S.L.",RE-04-46,2004; 2007,Negreira,A Coruña,Parque eólico,INEGA - Centrales eólicas operativas en Galicia,2026-06,PROP_005

#### 2.4 Importar datos de Tecnologia y Aerogeneradores

In [5]:
# Importar datos de información de tecnologia y aerogeneradores (Varias fuentes)
df_instalaciones_infoaerogeneradors = pd.read_excel(
    "../Data/Raw/Dummy/Generadores_y_Tecnologos/MaestroInstalacionesGalicia_InfoAdicional.xlsx"
)

# Incluir campo Id_Instalacion
df_instalaciones_infoaerogeneradors['Id_Instalacion'] = df_instalaciones_infoaerogeneradors['Clave Registro'] + "-" + df_instalaciones_infoaerogeneradors['Número de fase'].astype("string")

# Visualizar los resultados
df_instalaciones_infoaerogeneradors.head(5)

,Clave Registro,Nombre de Instalación,Municipio de la Instalación,Provincia de la Instalación,Número de fase,Número de Registro Autonómico Definitivo,Potencia Instalada KW,Grupo Normativo,Tipo de Inscripción,Fecha de Inscripción Definitiva,Num_aerogeneradores,Fabricante,Modelo,Potencia_unitaria_kw,Altura_buje_m,Diametro_rotor_m,Fuente,Id_Instalacion
0,RE-000845,PARQUE EOLICO ALABE-SOAN,Valadouro (O),Lugo,1,RE-05-09,19500,b.2.1,DEFINITIVA,1999-11-26 00:00:00,26,NEG Micon,NM 750/44,750,45,44,https://www.xunta.gal/dog/Publicados/1998/1998...,RE-000845-1
1,RE-000846,P. E. ALABE-NORDES,Valadouro (O),Lugo,1,RE-05-10,20250,b.2.1,DEFINITIVA,1999-11-26 00:00:00,27,NEG Micon,NM44/750,750,NaN,44,https://www.thewindpower.net/windfarm_es_1975_...,RE-000846-1
2,RE-000847,P. E. ALABE-CUADRAMON,Valadouro (O),Lugo,1,RE-05-11,18750,b.2.1,DEFINITIVA,1999-11-26 00:00:00,25,NEG Micon,NM44/750,750,NaN,44,https://www.thewindpower.net/windfarm_en_1958_...,RE-000847-1
3,RE-000849,P. E. SERRA DO CANDO,Lama (A),Pontevedra,1,RE-05-05,29230,b.2.1,DEFINITIVA,2000-11-02 00:00:00,44,Gamesa,G47 (43) / G52 (1),43×660; 1×850,NaN,NaN,https://www.renewableenergymagazine.com/ficher...,RE-000849-1
4,RE-000850,P. E. MONTE SEIXO-CANDO,Lama (A),Pontevedra,1,RE-99-57,34980,b.2.1,DEFINITIVA,2000-11-02 00:00:00,53,MADE,AE-46/I,660,45,46,Información generada por IA,RE-000850-1

### 3. Transformación de datos (Tabla D_Instalaciones)

#### 3.1 Inclusión de datos de Propietarios y Geografía

In [6]:
# Añadir columna de CCAA
df_instalaciones_galicia['Id_ccaa'] = 12

# Renombrar columnas
df_instalaciones_galicia = df_instalaciones_galicia.rename(columns={
    "Provincia de la Instalación": "Provincia",
    "Municipio de la Instalación": "Municipio",
    "Potencia Instalada KW": "Potencia_kw",
    "Grupo Normativo": "Cod_Grupo",
    "Clave Registro": "Clave_Registro",
    "Nombre de Instalación": "Nombre_Instalacion",
    "Número de fase": "Fase",
    "Tipo de Inscripción": "Tipo_Inscripcion",
    "Fecha de Inscripción Definitiva": "Fecha_Inscripcion",
    "Número de Registro Autonómico Definitivo": "Num_Registro"
    
})

# Incluir campo Id_Instalacion
df_instalaciones_galicia['Id_Instalacion'] = df_instalaciones_galicia['Clave_Registro'] + "-" + df_instalaciones_galicia['Fase'].astype("string")

# Incluir campo Instalacion
df_instalaciones_galicia['Instalacion'] = df_instalaciones_galicia['Id_Instalacion'] + " " + df_instalaciones_galicia['Nombre_Instalacion']

# Filtrar registros de instalaciones eólicas (valores "b.2.1" y "b.2.2" en columna Cod_Grupo)
df_instalaciones_galicia = df_instalaciones_galicia[
    (df_instalaciones_galicia["Cod_Grupo"] == "b.2.1") |
    (df_instalaciones_galicia["Cod_Grupo"] == "b.2.2")
]

#Substutuir valores erróneos en la columna "Provincia"
df_instalaciones_galicia["Provincia"] = (
    df_instalaciones_galicia["Provincia"].replace({
        "La Coruña": "A Coruña",
        "Orense": "Ourense"
    })
)

#Substutuir valores erróneos en la columna "Num_Registro"
df_instalaciones_galicia["Num_Registro"] = (
    df_instalaciones_galicia["Num_Registro"].replace({
        "RE-04-24 y RE-05-85": "RE-05-85","RE-01-25":"RE-05-56",   "REP-05-45":"RE-07-97",
        "RP-26-08":"RE-10-29", "REP-09-09":"RE-09-09", "RE-05-18":"RE-05-08","REP-06-40":"RE-06-40", "REP-06-05":"RE-06-05"
    })
)

#Join para incluir id_provincia
df_instalaciones_galicia = df_instalaciones_galicia.merge(
    df_provincias[
        ["Nombre_provincia","Cod-prv"]
    ],
    how="left",
    left_on="Provincia",
    right_on="Nombre_provincia"
)

#Eliminar valores entre "()" en la columna Num_Registro
columnas = ["Num_Registro"]
for col in columnas:
    df_instalaciones_galicia[col] = (
        df_instalaciones_galicia[col]
        .str.replace(r"\s*\([^)]*\)", "", regex=True)
        .str.strip()
    )

#Join para incluir el propietario de la instalación (información de Inega)
df_instalaciones_galicia = df_instalaciones_galicia.merge(
    df_propietarios_instalaciones[
        ["Registro_inega","Id_Propietario","Propietario"]
    ],
    how="left",
    left_on="Num_Registro",
    right_on="Registro_inega"
)

# Excluir registros con valores en blanco o null en Id_Propietario
df_instalaciones_galicia = df_instalaciones_galicia[
    df_instalaciones_galicia["Id_Propietario"].notna() &
    (df_instalaciones_galicia["Id_Propietario"].str.strip() != "")
]

#Eliminar columnas que no se necesitan
df_instalaciones_galicia = df_instalaciones_galicia.drop(
    columns=["Nombre_provincia", "Registro_inega"]
)

#Reemplazar valores erróneos en la columna Fecha_Inscripcion
df_instalaciones_galicia["Fecha_Inscripcion"] = pd.to_datetime(
    df_instalaciones_galicia["Fecha_Inscripcion"].replace("N/D", pd.NA),
    errors="coerce"
)

#Reordenar columnas
df_instalaciones_galicia = df_instalaciones_galicia[['Id_Instalacion','Clave_Registro', 'Nombre_Instalacion', 'Instalacion',
                                                     'Id_Propietario','Propietario','Id_ccaa', 'Cod-prv','Provincia','Municipio',
                                                     'Num_Registro','Cod_Grupo', 'Fase',  'Potencia_kw',  'Tipo_Inscripcion',
                                                     'Fecha_Inscripcion']]

# Visualizar los resultados
df_instalaciones_galicia

,Id_Instalacion,Clave_Registro,Nombre_Instalacion,Instalacion,Id_Propietario,Propietario,Id_ccaa,Cod-prv,Provincia,Municipio,Num_Registro,Cod_Grupo,Fase,Potencia_kw,Tipo_Inscripcion,Fecha_Inscripcion
0,RE-000845-1,RE-000845,PARQUE EOLICO ALABE-SOAN,RE-000845-1 PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-09,b.2.1,1,19500.0,DEFINITIVA,1999-11-26
1,RE-000846-1,RE-000846,P. E. ALABE-NORDES,RE-000846-1 P. E. ALABE-NORDES,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-10,b.2.1,1,20250.0,DEFINITIVA,1999-11-26
2,RE-000847-1,RE-000847,P. E. ALABE-CUADRAMON,RE-000847-1 P. E. ALABE-CUADRAMON,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-11,b.2.1,1,18750.0,DEFINITIVA,1999-11-26
3,RE-000849-1,RE-000849,P. E. SERRA DO CANDO,RE-000849-1 P. E. SERRA DO CANDO,PROP_047,"Olivento S.L., Sociedade Unipersoal",12,36,Pontevedra,Lama (A),RE-05-05,b.2.1,1,29230.0,DEFINITIVA,2000-11-02
4,RE-000850-1,RE-000850,P. E. MONTE SEIXO-CANDO,RE-000850-1 P. E. MONTE SEIXO-CANDO,PROP_047,"Olivento S.L., Sociedade Unipersoal",12,36,Pontevedra,Lama (A),RE-99-57,b.2.1,1,34980.0,DEFINITIVA,2000-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,RE436-0320-1,RE436-0320,P.E MONSEIVANE,RE436-0320-1 P.E MONSEIVANE,PROP_004,"EDP Renovables España, S.L.",12,27,Lugo,Abadín,RE-04-36,b.2.1,1,41400.0,DEFINITIVA,2004-08-31
206,RE436-0353-1,RE436-0353,P.E. AMPLIACION DE ALABE-SOAN (AMPL. DE RE-4387),RE436-0353-1 P.E. AMPLIACION DE ALABE-SOAN (AM...,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Muras,RE-05-62,b.2.1,1,12750.0,DEFINITIVA,2004-06-15
207,RE436-0478-2,RE436-0478,P.E. CORZAN,RE436-0478-2 P.E. CORZAN,PROP_005,"Enel Green Power España, S.L.",12,15,A Coruña,Negreira,RE-04-46,b.2.1,2,7200.0,DEFINITIVA,2009-06-15
208,RE436-0478-1,RE436-0478,P.E. CORZAN,RE436-0478-1 P.E. CORZAN,PROP_005,"Enel Green Power España, S.L.",12,15,A Coruña,Negreira,RE-04-46,b.2.1,1,36000.0,DEFINITIVA,2004-11-02
209,RE436-0604-1,RE436-0604,P.E. LA CELAYA,RE436-0604-1 P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",12,27,Lugo,Vilalba,RE-05-19,b.2.1,1,28800.0,DEFINITIVA,2005-01-26

#### 3.2 Inclusión de datos de Aerogeneradores y Tecnología

In [7]:
#Join para incluir información adicional de aerogneradores, tecnología y otros
df_instalaciones_galicia_vf = df_instalaciones_galicia.merge(
    df_instalaciones_infoaerogeneradors[
        ["Id_Instalacion",'Num_aerogeneradores', 'Fabricante',
       'Modelo', 'Potencia_unitaria_kw']
    ],
    how="left",
    left_on="Id_Instalacion",
    right_on="Id_Instalacion"
)

#Reordenar columnas
df_instalaciones_galicia_vf = df_instalaciones_galicia_vf[['Id_Instalacion', 'Clave_Registro', 'Nombre_Instalacion',
       'Id_Propietario', 'Propietario', 'Id_ccaa', 'Cod-prv', 'Provincia',
       'Municipio', 'Num_Registro', 'Cod_Grupo','Potencia_kw', 'Fase', 'Num_aerogeneradores', 'Fabricante', 'Modelo',
       'Potencia_unitaria_kw','Tipo_Inscripcion', 'Fecha_Inscripcion']]

df_instalaciones_galicia_vf

,Id_Instalacion,Clave_Registro,Nombre_Instalacion,Id_Propietario,Propietario,Id_ccaa,Cod-prv,Provincia,Municipio,Num_Registro,Cod_Grupo,Potencia_kw,Fase,Num_aerogeneradores,Fabricante,Modelo,Potencia_unitaria_kw,Tipo_Inscripcion,Fecha_Inscripcion
0,RE-000845-1,RE-000845,PARQUE EOLICO ALABE-SOAN,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-09,b.2.1,19500.0,1,26,NEG Micon,NM 750/44,750,DEFINITIVA,1999-11-26
1,RE-000846-1,RE-000846,P. E. ALABE-NORDES,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-10,b.2.1,20250.0,1,27,NEG Micon,NM44/750,750,DEFINITIVA,1999-11-26
2,RE-000847-1,RE-000847,P. E. ALABE-CUADRAMON,PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Valadouro (O),RE-05-11,b.2.1,18750.0,1,25,NEG Micon,NM44/750,750,DEFINITIVA,1999-11-26
3,RE-000849-1,RE-000849,P. E. SERRA DO CANDO,PROP_047,"Olivento S.L., Sociedade Unipersoal",12,36,Pontevedra,Lama (A),RE-05-05,b.2.1,29230.0,1,44,Gamesa,G47 (43) / G52 (1),43×660; 1×850,DEFINITIVA,2000-11-02
4,RE-000850-1,RE-000850,P. E. MONTE SEIXO-CANDO,PROP_047,"Olivento S.L., Sociedade Unipersoal",12,36,Pontevedra,Lama (A),RE-99-57,b.2.1,34980.0,1,53,MADE,AE-46/I,660,DEFINITIVA,2000-11-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
194,RE436-0320-1,RE436-0320,P.E MONSEIVANE,PROP_004,"EDP Renovables España, S.L.",12,27,Lugo,Abadín,RE-04-36,b.2.1,41400.0,1,49,Gamesa,G52,850,DEFINITIVA,2004-08-31
195,RE436-0353-1,RE436-0353,P.E. AMPLIACION DE ALABE-SOAN (AMPL. DE RE-4387),PROP_001,"Acciona Eólica de Galicia, S.A.",12,27,Lugo,Muras,RE-05-62,b.2.1,12750.0,1,15,Gamesa,G52,850,DEFINITIVA,2004-06-15
196,RE436-0478-2,RE436-0478,P.E. CORZAN,PROP_005,"Enel Green Power España, S.L.",12,15,A Coruña,Negreira,RE-04-46,b.2.1,7200.0,2,8,Gamesa,G52,850,DEFINITIVA,2009-06-15
197,RE436-0478-1,RE436-0478,P.E. CORZAN,PROP_005,"Enel Green Power España, S.L.",12,15,A Coruña,Negreira,RE-04-46,b.2.1,36000.0,1,18,Vestas,V90,2000,DEFINITIVA,2004-11-02
198,RE436-0604-1,RE436-0604,P.E. LA CELAYA,PROP_004,"EDP Renovables España, S.L.",12,27,Lugo,Vilalba,RE-05-19,b.2.1,28800.0,1,34,Gamesa,G52,850,DEFINITIVA,2005-01-26

### 4. Exportar los datos a Excel

#### 4.1 Almacenamiento Tabla D_Instalaciones (previa)

In [8]:
# Exportar los resultados a Excel
df_instalaciones_galicia.to_excel("../Data/Silver/MaestroInstalacionesGalicia_prev.xlsx", index=False)

#### 4.2 Almacenamiento Tabla D_Instalaciones (final)

In [9]:
# Exportar los resultados a Excel
df_instalaciones_galicia_vf.to_excel("../Data/Gold/Dim/MaestroInstalacionesGalicia.xlsx", index=False)